import type { ImageDraft } from "../domain/product-images";
import type { ProductInput } from "../validations";

export type Product = {
  id: number;
  name: string;
  slug: string;
  description: string | null;
  sku: string;
  price: number;
  purchasePrice: number;
  categoryId: number | null;
  distributorCode: string | null;
  stock: number;
  minStock: number;
  warrantyMonths: number | null;
  active: boolean;
  // Derived from product_images (primary first, then display order) — never
  // stored on the product itself. For thumbnails in lists.
  primaryImageUri: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ProductImage = {
  id: number;
  productId: number;
  url: string;
  alt: string | null;
  displayOrder: number;
  isPrimary: boolean;
};

export type ProductWithImages = Product & {
  // Ordered by displayOrder; exactly one isPrimary when non-empty.
  images: ProductImage[];
};

// sku is auto-generated by ProductsRepo.create, never accepted as input —
// it's already absent from ProductInput/productSchema.
export type CreateProductInput = ProductInput;
export type UpdateProductInput = Partial<CreateProductInput>;

export interface ProductsRepo {
  list(): Promise<Product[]>;
  getById(id: number): Promise<ProductWithImages | null>;
  findByDistributorCode(code: string): Promise<Product | null>;
  // `images`, when given, replaces the product's whole gallery in the same
  // transaction as the product write (order = display order; normalized so
  // exactly one is primary). Omitted on update = gallery left untouched.
  // Files of photos dropped from the gallery are deleted from disk.
  create(data: CreateProductInput, images?: ImageDraft[]): Promise<Product>;
  update(id: number, data: UpdateProductInput, images?: ImageDraft[]): Promise<Product>;
  deactivate(id: number): Promise<void>;
}
