import type { ProductInput } from "../validations";

export type Product = {
  id: number;
  name: string;
  slug: string;
  description: string | null;
  sku: string;
  price: number;
  purchasePrice: number;
  categoryId: number | null;
  stock: number;
  minStock: number;
  warrantyMonths: number | null;
  active: boolean;
  imageUri: string | null;
  createdAt: string;
  updatedAt: string;
};

// sku is auto-generated by ProductsRepo.create, never accepted as input —
// it's already absent from ProductInput/productSchema.
export type CreateProductInput = ProductInput;
export type UpdateProductInput = Partial<CreateProductInput>;

export interface ProductsRepo {
  list(): Promise<Product[]>;
  getById(id: number): Promise<Product | null>;
  create(data: CreateProductInput): Promise<Product>;
  update(id: number, data: UpdateProductInput): Promise<Product>;
  deactivate(id: number): Promise<void>;
}
